### ISSUE TITLE
Failure during "Set up users" task

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-infrastructure#13]
When I run the real playbook against one of our servers, I'm seeing a failure in this step:

```bash
TASK [Set up users] *****************************************************************************************************************
fatal: [192.241.253.217]: FAILED! => {"msg": "Unexpected failure in finding the lookup named '{{ users }}' in the available lookup plugins"}
	to retry, use: --limit @/Users/mgardner/labs-infrastructure/playbooks/base.retry

PLAY RECAP **************************************************************************************************************************
192.241.253.217            : ok=13   changed=6    unreachable=0    failed=1
```

I see users in our [base playbook](https://github.com/NYCPlanning/labs-infrastructure/blob/master/playbooks/base.yml). Is there some Ansible DSL for these variables?

**Comment by afeld** [comment]
Hmmmmm. We can look at this in person today.

**Comment by afeld** [comment]
This was in check mode where the user didn't exist. Not sure if there's a great workaround, so may have to deal with things like that as they come up.
